# Site settings
title: BAD days
description: A tutorial for anyone wanting to use SageMathCloud for teaching
baseurl: "/BAD_days"
url: "http://trallard.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Additional gems
#gems:
  #- 
