# Site settings
title: BAD days
description: Bioinformatics Awareness Days (BAD days)
baseurl: "/BAD_days"
url: "http://trallard.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Additional gems
#gems:
  #-
