# Site settings
title: BAD days
description: Bioinformatics Awareness Days (BAD days)
baseurl: "/BAD_days"
url: "http://trallard.github.io" # the base hostname & protocol for your site


# About
author:
  name: Tania Allard



# Build settings
markdown: kramdown
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - jekyll.py
  - jekyll.tpl

# to ensure the links work properly
permalink: pretty

# Additional gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# SASS directory
sass:
  style: compressed
  sass_dir: _sass
